### PR TITLE
Mock up presentation outlines for front page quiz

### PR DESCRIPTION
**Pull request by tapaswenipathak**
Ref https://github.com/ipfs/docs/issues/205

Kicking the tires with few thoughts -

- [ ] Wireframes and Mockups - @tapaswenipathak

Hey people, what is the communication channel folks are available than scheduled calls which can be hard.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Thanks, @tapaswenipathak! The 1500h UTC Monday call is our primary weekly check-in, and you can always find notes from that meeting (and videos of it) here: https://docs.google.com/document/d/1EOD-pJi4GvRmGi9HHocgVV8uVHMFIZlyVgJDkvC3DQ4/edit#

If that's not a good time, we also communicate quite a bit using GitHub issues. And if you've got a specific issue you'd like to discuss in a more one-on-one format, we can always figure something out.

I'm traveling at the moment but I'm sure @ericronne and I will touch base on this quiz more very soon :)

**Comment by tapaswenipathak** [comment]
I will be there or if you can leave notes for the ticket will do as well. Best, if you have any IRC sort of communication channel where we can chat about the ticket. I am super interested in writing on the ticket and closing that out.

**Comment by jessicaschilling** [comment]
Hi @tapaswenipathak -- I'm going to go ahead and close out this issue without merging for now, but capture your very useful question structure in the notes in related issue #204. If you look through the description of #204, you'll see that the plan is to start with a single-question quiz that can be expanded later into a more complete "choose your own adventure" style metaphor for moving through IPFS documentation. Your notes are going to be very useful as we develop that, so thank you! (And please keep an eye on #204 as it develops.) 😄

**Comment by tapaswenipathak** [comment]
Thanks for finding the notes useful @jessicaschilling.

**Pull request closed without merging**
