### PR TITLE
update deps to fix security warnings

### PR DESCRIPTION
**Pull request by Stebalien**
Also fix golang API docs generation.

### CODE REVIEW

**Comment by Stebalien** [comment]
@olizilla could you update the go version in the docker container "olizilla/ipfs-dns-deploy" to 1.12?

**Comment by jessicaschilling** [comment]
@Stebalien @olizilla Just checking in on the progress of this one. Thanks!

**Comment by olizilla** [comment]
The docker image responsible for building the docs site is https://github.com/ipfs/ci-websites

I've raised an issue there to update it https://github.com/ipfs/ci-websites/issues/6

I'll get to it next week if no one beats me to it.

**Comment by olizilla** [comment]
Teamwork makes the dream work. Steven made a PR to [update the deps](https://github.com/ipfs/ci-websites/pull/7). I tweaked it, and now we have the ci-websites repo auto building it's docker image to dockerhub and all the auto magic should be back

**Comment by jessicaschilling** [comment]
@olizilla -- Beautiful! Want to merge and close?

**Comment by olizilla** [comment]
@jessicaschilling done!

**Comment by jessicaschilling** [comment]
@olizilla Thanks!

**Pull request merged**
