### PR TITLE
On legacy, adds link to each page's equivalent page on docs beta

### PR DESCRIPTION
**Pull request by jessicaschilling**
**WARNING: DO NOT MERGE until we are ready to launch beta!**

- Adds callout on each legacy site page that visually matches @ericronne's layout in https://github.com/ipfs/docs/issues/341#issuecomment-553577494 (also responsive to mobile)
- Links in each page's callout go to the appropriate equivalent page on the beta; this is done using a variable in each page's front matter and a little template for the callout in the site partials
- Partially addresses #341 (but doesn't close; still need the reciprocal links added to the beta site)

image

### CODE REVIEW

**Comment by jessicaschilling** [comment]
@ericronne @cwaring -- can you please have a look? Screenshot in the original comment, but you should also be able to look at the CircleCI staging. NOTE: DO NOT MERGE until we are ready to launch beta! ;)

**Comment by cwaring** [comment]
This looks great! Smart use of the front matter to link the pages together.

**Comment by jessicaschilling** [comment]
@ericronne Thanks for the fixing! Calling this one done ... I'll merge later when we're ready.

**Comment by ericronne** [comment]
Cool. The blue-on-blue link-color contrast is just shy of 508 compliance, but as this site is destined for the mothballs …

**Pull request merged**
