### PR TITLE
Simplified introduction paragraph. Issue #426.

### PR DESCRIPTION
**Pull request by alex-example**
This PR addresses issue #426.

### CODE REVIEW

**Comment by johnnymatthews** [comment]
Looks good to me! Thanks for the contribution.

**Comment by cwaring** [comment]
@johnnymatthews heads up: it looks like this was PR'd to the wrong repo. The old docs site should either be frozen now or all changes also need to get ported upstream to the new beta, otherwise this content will be lost once it is deprecated.

**Comment by jessicaschilling** [comment]
@johnnymatthews @cwaring Let’s *not* make any further changes to legacy site content. Duplicating work isn’t a good use of our time at this point.

**Comment by johnnymatthews** [comment]
This PR was made as an example for a _How to Contribute to the Docs_ video and tutorial. The actual content of the PR isn't particularly important (the account @alex-example changed one line). The PR and merge were both done by me. 

I made the changes in this repo so that we wouldn't have to re-record anything when the current [docs.ipfs.io](https://docs.ipfs.io) is deprecated and the `ipfs-docs-v2` is overwrites/merges into this one.

**Comment by jessicaschilling** [comment]
Ah! That makes sense.

**Pull request merged**
