### PR TITLE
Build markdown API docs for JS and Go packages

### PR DESCRIPTION
**Pull request by ghost**
This hacky little script builds API reference docs in markdown for a given JS or Go package. It's not wired up to the build yet since it depends on a change in [aegir](https://github.com/ipfs/aegir).

Examples:
```
> ./package.sh github.com/ipfs/js-ipfs-api master content/pkg/
> ./package.sh github.com/ipfs/go-ipfs-api master content/pkg/
```

These end up in `content/pkg/{js,go}-ipfs-api` where they're picked up by Hugo, which renders them at `https://docsdev.ipfs.team/pkg/{js,go}-ipfs-api`.

These currently both render godoc2md's and documentation.js's default markdown templates -- we can customize them as we see fit.

### CODE REVIEW

**Comment by lgierth** [comment]
Examples:
- js-ipfs-api: https://ipfs.io/ipfs/QmVjycugYoQXJhFAvQGUp8XZW7pu2TRkEqytGAWeWs9q4n/pkg/js-ipfs-api/
- go-ipfs-api: https://ipfs.io/ipfs/QmVjycugYoQXJhFAvQGUp8XZW7pu2TRkEqytGAWeWs9q4n/pkg/go-ipfs-api/

**Review by magik6k — APPROVED** [review]
LGTM, though in future it would be nice to split this into sections a bit more.

BTW, there is https://github.com/ipfs/docs/tree/master/content/api directory for APIs

**Comment by magik6k** [comment]
Oh, and for Go the links in index don't work

**Comment by lgierth** [comment]
> BTW, there is https://github.com/ipfs/docs/tree/master/content/api directory for APIs

We should have much more package docs than just js-ipfs-api and go-ipfs-api though (these were just examples).

/api can hold the HTTP docs and concepts -- but yeah this just again hints at the huge confusion of terms that we've let grow over the years. When we say API, wtf do we actually mean? Core API, HTTP API, :5001, the *-api packages? But that's for another discussion.

> Oh, and for Go the links in index don't work

Yeah I noticed that too -- something to do with Hugo's markdown renderer. Something to fix in one of the next few PRs :)

**Comment by lgierth** [comment]
> though in future it would be nice to split this into sections a bit more.

We can do that later. I think we shouldn't start with an empty structure skeleton and then fill it with content -- we should do it the other way around: develop structure as we add content

**Pull request merged**
