### PR TITLE
Small formatting and layout changes

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
Working on making some small layout and language improvements to the basic usage doc, mostly to clarify some concepts, polish a little language.

### CODE REVIEW

**Comment by meiqimichelle** [comment]
Hi @ChrisChinchilla ~ thank you for these edits! Are you still working on this, or should we resolve conflicts and (hopefully!) merge?

**Comment by ChrisChinchilla** [comment]
@meiqimichelle Ah no, this was just from a hack event.

**Comment by meiqimichelle** [comment]
Got it! I'll see about resolving merge conflicts and 🚀 . Thank you again!

**Comment by jessicaschilling** [comment]
@meiqimichelle -- are you able to resolve merge conflicts so we can get this one out the door? Thanks!

**Comment by jessicaschilling** [comment]
@meiqimichelle Never mind! Simple conflict, found it myself. (Content was added at a later date for Companion, which we'll of course want to keep.)

**Pull request merged**
