### PR TITLE
Add “Edit this page in GitHub” links

### LINKED ISSUE #103: Add “Edit this page in GitHub” links
Maybe I'm just used to OSS documentation to work this way, but I expected the GitHub icon to take me to the file on GitHub rather than a link to the IPFS organization.

Would make it really simple to contribute if it took users directly to the file.

### PR DESCRIPTION
**Pull request by andrew**
Fixes #103

### CODE REVIEW

**Comment by olizilla** [comment]
@andrew would you mind mergin in master into this branch so we can let CI do it's thing and get a preview of the change?

**Comment by andrew** [comment]
Rebased against master, not seeing any CI run though?

**Comment by olizilla** [comment]
Needs more `content` in the url. I've fixed up the `make dev` command so it's actually possible to try out changes like these! I'll fix the url here.

**Comment by andrew** [comment]
🎉

**Pull request merged**
