### PR TITLE
fix godoc building and update

### PR DESCRIPTION
**Pull request by Stebalien**
I went ahead and nuked the Go API docs:

1. We weren't hosting our own JS API docs.
2. Our Go API docs were inferior to godoc.org.
3. Devs will be familiar with godoc.org as that's what we link to from our repos (also what every other project under the sun uses).
4. Fixing this wasn't worth the effort.

### CODE REVIEW

**Comment by jessicaschilling** [comment]
Closes #276

**Comment by Mr0grog** [comment]
FWIW, one of the main reasons we didn’t do this initially was to support #66, which godoc.org does not have great support for. NOT trying to disagree with this change (it’s probably the right move!); just want to provide some planning context if versioned API reference docs are still a major goal (I can’t see the spreadsheet linked from #66, but the comment makes it sound like it still is).

**Comment by jessicaschilling** [comment]
@Mr0grog Thanks for finding that broken spreadsheet link! Spreadsheet creep -> separated the features list into this: https://docs.google.com/spreadsheets/d/1YJ8yuzoNeunVr3ftvm7x2nIKsj7IlTrsfuy71ZnGg6Y/edit#gid=785339355

Versioning is definitely a strong point on that roadmap -- specifically in API dictionaries but just in the docs as a whole.

Also, hi! I've really appreciated the opportunity to lurk hard on all your previous work. 😄

**Comment by Stebalien** [comment]
Hm. You're right. Go module support in go doc (https://github.com/golang/gddo/issues/567) should fix this but it's unclear how long that will take to land.

**Comment by Mr0grog** [comment]
Sweet, I had been wondering if godoc versioning would wind up coming along for the ride!

> Also, hi! I've really appreciated the opportunity to lurk hard on all your previous work.

Awesome, happy if it’s helpful. 👋

**Pull request merged**
