### PR TITLE
Re-build the theme/layout

### LINKED ISSUE #77: Rewrite Theme/Layout
In #68, I mangled a theme that was already a bit broken to get some basic docs out the door. However, the code for it is *really* terrible.

1. Something in the JS goes off the rails pretty quickly and starts eating the CPU in a tight loop. This is really bad.
2. We have some ugly CSS selectors that exist just to override stuff built into the theme.
3. There are features that are just commented out or hidden (e.g. search); they should actually be removed.
4. The nav implementation is kind of horrifying. I think there are limits to what we can make nice with Hugo, but it can be better than what it is now. From #68:

    > The menu/nav system is a little nutty and flips between an old system of enumerating all the contents of a section and using Hugo’s built-in menu system (originally needed because of the external links, but then I also made this ugly hack). At any rate, this really needs cleanup:
    > 
    > - We can use the old method of enumerating the contents of each section, with hacks like the FAQ’s external frontmatter field to get external links. It’s not well supported in Hugo and results in some really complicated code, but it does keep things visible in the directory structure instead of in the config.toml file.
    > 
    > - We can just wholesale use the Hugo menu system, which is well supported and more clean, if limited in functionality.
    > 
    > - We can ditch both those and just encode the menus in the layout.

Basically, we probably need to gut the JS and CSS we have and start over. It’s ok if it’s pretty minimal, because most of the existing functionality is turned off or broken anyway.

### PR DESCRIPTION
**Pull request by Mr0grog**
~**Work-in-progress; DO NOT MERGE!**~ (UPDATE: this is mergeable now)

We are removing the old theme (which was broken in a number of ways) and rewriting a *very* minimal and simple version. A future PR will focus on an actual redesign, but here we're just making it shippable.

MUCH ❤️to @eocarragain for help here!

Fixes #77

### CODE REVIEW

**Comment by Mr0grog** [comment]
I still need to redo the small screen menu, but that should mostly be all that’s left at this point.

**Comment by Mr0grog** [comment]
OK, this should be ready to merge. Again, this is just supposed to be a minimal reproduction of what we previously had with less JS and with readable code. There are a few minor layout/design tweaks (the footer has moved, the menu has some better accessibility features), but it’s not meant to be too special and is likely something we’ll just throw away in a later redesign.

Care to review at all, @lgierth, @kyledrake, @olizilla? (I’ll merge after one of you 👍)

Once this is merged, this site should be ready to push live! (Still lots to improve on it, but it’s at least usable.)

**Comment by lgierth** [comment]
This looks great :):):)

**Comment by Mr0grog** [comment]
MERGIFYING

**Pull request merged**
